[tox]
envlist = pytest, flake8, deptry

[testenv]
basepython = python3.10
set_env =
    VIRTUALENV_PIP = 24.0
    VIRTUALENV_SETUPTOOLS = 68.2.2
    VIRTUALENV_WHEEL = 0.42.0
deps =
    pip<24.1
    setuptools<70

[testenv:pytest]
usedevelop = True
commands =
  py.test tests \
    --durations=10 \
    --cov radar \
    --cov-config .coveragerc \
    --cov-report html \
    --cov-report term
deps =
    {[testenv]deps}
    -r{toxinidir}/dev-requirements.txt
    -r{toxinidir}/requirements.txt

[testenv:flake8]
commands =
  flake8 radar setup.py tests scripts
deps =
    flake8

[testenv:deptry]
description = Run deptry to check for unused and missing dependencies
deps =
    deptry
commands =
    # Never fail GitActions
    python -c "import subprocess; subprocess.call(['deptry', '.'])"

[flake8]
max-line-length = 120
application-import-names = radar,tests
import-order-style = google
