[tox]
# These are the environments that tox will create/run
envlist = ruff, ruff-lint, mypy, deptry

# This is an application, not a library, so we don't need to treat it as one
skipsdist = True

[testenv]
allowlist_externals = poetry
commands_pre =
    poetry sync --no-root

[testenv:ruff]
description = Check code formatting with ruff.
commands =
    poetry run ruff format . --check --exclude ./migrations

[testenv:ruff-lint]
description = Lint the code with ruff.
commands =
    poetry run ruff check . --exclude ./migrations

[testenv:mypy]
description = Execute static analysis with mypy.
commands =
    poetry run mypy radar/ tests/ scripts/

[testenv:deptry]
description = Run deptry to check for unused and missing dependencies.
commands =
    # Leading "-" tells tox to ignore the exit code (never fail CI)
    - poetry run deptry .
