[tox]
# These are the environments that tox will create/run
envlist = ruff, ruff-lint, mypy, deptry

# This is an application, not a library, so we don't need to treat it as one
skipsdist = True

# This section provides default settings for the environments above
[testenv]
allowlist_externals = poetry
commands =
    poetry install -v

[testenv:ruff]
description = 'Check code style with Black'
allowlist_externals = poetry
commands = poetry run ruff format . --check

[testenv:ruff-lint]
description = 'Execute static analysis with pylint.'
allowlist_externals = poetry
commands = poetry run ruff check .

[testenv:mypy]
description = 'Execute static analysis with mypy.'
allowlist_externals = poetry
commands_pre =
  poetry install --no-root --sync
commands =
	poetry run mypy radar/ tests/ scripts/
deps =
	mypy
	types-WTForms
	types-jsonschema
	types-python-dateutil
	types-pytz
	types-setuptools
	types-zxcvbn

[testenv:deptry]
description = Run deptry to check for unused and missing dependencies
allowlist_externals = poetry
deps = deptry
commands =
    # Never fail GitActions
    python -c "import subprocess; subprocess.call(['poetry', 'run', 'deptry', '.'])"
