# =====
# Roles
# =====

UNIT_IT = 'IT'
UNIT_ADMIN = 'ADMIN'
UNIT_CLINICIAN = 'CLINICIAN'
UNIT_SENIOR_CLINICIAN = 'SENIOR_CLINICIAN'

DISEASE_GROUP_SENIOR_RESEARCHER = 'SENIOR_RESEARCHER'
DISEASE_GROUP_RESEARCHER = 'RESEARCHER'

UNIT_ROLE_NAMES = {
    UNIT_IT: 'IT',
    UNIT_ADMIN: 'Admin',
    UNIT_CLINICIAN: 'Clinician',
    UNIT_SENIOR_CLINICIAN: 'Senior Clinician',
}

DISEASE_GROUP_ROLE_NAMES = {
    DISEASE_GROUP_SENIOR_RESEARCHER: 'Senior Researcher',
    DISEASE_GROUP_RESEARCHER: 'Researcher',
}

# Ascending access level
UNIT_ROLES = [
    UNIT_CLINICIAN,
    UNIT_SENIOR_CLINICIAN,
    UNIT_ADMIN,
    UNIT_IT,
]

# Ascending access level
DISEASE_GROUP_ROLES = [
    DISEASE_GROUP_RESEARCHER,
    DISEASE_GROUP_SENIOR_RESEARCHER,
]

# Special roles

UNIT_GOD = 'GOD'
DISEASE_GROUP_GOD = 'GOD'

# ===========
# Permissions
# ===========

# Unit permissions

UNIT_VIEW_PATIENT_ROLES = [
    UNIT_GOD,
    UNIT_CLINICIAN,
    UNIT_SENIOR_CLINICIAN,
    UNIT_ADMIN,
]

UNIT_EDIT_PATIENT_ROLES = [
    UNIT_GOD,
    UNIT_CLINICIAN,
    UNIT_SENIOR_CLINICIAN,
]

UNIT_VIEW_DEMOGRAPHICS_ROLES = [
    UNIT_GOD,
    UNIT_CLINICIAN,
    UNIT_SENIOR_CLINICIAN,
    UNIT_ADMIN,
]

UNIT_VIEW_USER_ROLES = [
    UNIT_GOD,
    UNIT_IT,
    UNIT_ADMIN,
    UNIT_SENIOR_CLINICIAN,
]

UNIT_MANAGED_ROLES = {
    UNIT_IT: [
        UNIT_CLINICIAN,
    ],
    UNIT_ADMIN: [
        UNIT_CLINICIAN,
    ],
    UNIT_SENIOR_CLINICIAN: [
        UNIT_CLINICIAN,
    ],
}

# Disease group permissions

DISEASE_GROUP_VIEW_PATIENT_ROLES = [
    DISEASE_GROUP_SENIOR_RESEARCHER,
    DISEASE_GROUP_RESEARCHER,
    DISEASE_GROUP_GOD
]

DISEASE_GROUP_VIEW_DEMOGRAPHICS_ROLES = [
    DISEASE_GROUP_SENIOR_RESEARCHER,
    DISEASE_GROUP_GOD
]

DISEASE_GROUP_VIEW_USER_ROLES = [
    DISEASE_GROUP_GOD
]

DISEASE_GROUP_MANAGED_ROLES = {
    DISEASE_GROUP_SENIOR_RESEARCHER: [
        DISEASE_GROUP_SENIOR_RESEARCHER,
        DISEASE_GROUP_RESEARCHER
    ]
}