UNIT_ADMIN = 'UNIT_ADMIN'
CLINICIAN = 'CLINICIAN'
SENIOR_CLINICIAN = 'SENIOR_CLINICIAN'
SENIOR_RESEARCHER = 'SENIOR_RESEARCHER'
RESEARCHER = 'RESEARCHER'
UNIT_GOD = 'UNIT_GOD'
DISEASE_GROUP_GOD = 'DISEASE_GROUP_GOD'

UNIT_VIEW_PATIENT_ROLES = [
    CLINICIAN,
    SENIOR_CLINICIAN,
    UNIT_ADMIN,
    UNIT_GOD,
]

UNIT_EDIT_PATIENT_ROLES = [
    CLINICIAN,
    SENIOR_CLINICIAN,
    UNIT_GOD,
]

UNIT_VIEW_DEMOGRAPHICS_ROLES = [
    CLINICIAN,
    SENIOR_CLINICIAN,
    UNIT_ADMIN,
    UNIT_GOD,
]

UNIT_VIEW_USER_ROLES = [
    UNIT_GOD
]

DISEASE_GROUP_VIEW_PATIENT_ROLES = [
    SENIOR_RESEARCHER,
    RESEARCHER,
    DISEASE_GROUP_GOD
]

DISEASE_GROUP_VIEW_DEMOGRAPHICS_ROLES = [
    SENIOR_RESEARCHER,
    DISEASE_GROUP_GOD
]

DISEASE_GROUP_VIEW_USER_ROLES = [
    UNIT_GOD
]