"""migrate data

Revision ID: edb5ca91f83d
Revises: f20cde35e83c
Create Date: 2017-03-13 10:49:02.232044

"""
from collections import OrderedDict

from alembic import op
import sqlalchemy as sa

from radar.app import Radar
from radar.database import db
from radar.models.ethnicities import Ethnicity
from radar.models.patient_demographics import PatientDemographics


# revision identifiers, used by Alembic.
revision = 'edb5ca91f83d'
down_revision = 'f20cde35e83c'
branch_labels = None
depends_on = None

ETHNICITIES = OrderedDict([
    ('A', 'White - British'),
    ('B', 'White - Irish'),
    ('C', 'Other White Background'),
    ('D', 'Mixed - White and Black Caribbean'),
    ('E', 'Mixed - White and Black African'),
    ('F', 'Mixed - White and Asian'),
    ('G', 'Other Mixed Background'),
    ('H', 'Asian or Asian British - Indian'),
    ('J', 'Asian or Asian British - Pakistani'),
    ('K', 'Asian or Asian British - Bangladeshi'),
    ('L', 'Other Asian Background'),
    ('M', 'Black Carribean'),
    ('N', 'Black African'),
    ('P', 'Other Black Background'),
    ('R', 'Chinese'),
    ('S', 'Other Ethnic Background'),
    ('Z', 'Refused / Not Stated'),
])


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    app = Radar()
    with app.app_context():
        for code, label in ETHNICITIES.items():

            db.session.add(Ethnicity(code=code, label=label))
            db.session.commit()

        db.session.execute('update patient_demographics set ethnicity_id = (select id from ethnicities where code = ethnicity)')
        db.session.commit()

    op.drop_column('patient_demographics', 'ethnicity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.orm import sessionmaker
    Session = sessionmaker()
    op.add_column('patient_demographics', sa.Column('ethnicity', sa.String(), autoincrement=False, nullable=True))
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute('update patient_demographics set ethnicity = (select code from ethnicities where id = ethnicity_id)')
    session.commit()

    #app = Radar()
    #with app.app_context():
    #    db.session.commit()

    #    db.session.execute('update patient_demographics set ethnicity = (select code from ethnicities where id = ethnicity_id)')
    #    db.session.commit()
    # ### end Alembic commands ###
