PHENOTYPE_MAP = {
    1: 'Autoimmune Disease',
    2: 'Mental Retardation Syndrome',
    3: 'Polydactyly',
    4: 'Blindness',
    5: 'Deafness',
    6: 'Cardiomyopathy',
    7: 'Congenital CMV',
    8: 'TORCH Syndrome',
    9: 'Diabetes',
    10: 'Microcephaly',
    11: 'Nail-Patella Syndrome',
    12: 'Cardiac Anomalies',
    13: 'Hepatitis B',
    14: 'Hepatitis C',
    15: 'CNS Abnormalitites',
    16: 'Spondyloepiphyseal Dysplasia',
    17: 'Microcoria',
    18: 'Male Pseudohermaphroditism',
}
