"""added control patient

Revision ID: 1108aad493bc
Revises: c747d6f9d206
Create Date: 2017-08-21 06:33:11.037000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1108aad493bc'
down_revision = 'c747d6f9d206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('control', sa.Boolean(), server_default=sa.text(u'false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'control')
    # ### end Alembic commands ###
