"""Added reconsent letter dates

Revision ID: 1da683d8e7b0
Revises: 544aa435c17d
Create Date: 2019-07-29 12:37:13.844495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da683d8e7b0'
down_revision = '544aa435c17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_consents', sa.Column('reconsent_letter_returned_date', sa.Date(), nullable=True))
    op.add_column('patient_consents', sa.Column('reconsent_letter_sent_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_consents', 'reconsent_letter_sent_date')
    op.drop_column('patient_consents', 'reconsent_letter_returned_date')
    # ### end Alembic commands ###
