"""add country to group

Revision ID: 1f816aa90812
Revises: edb5ca91f83d
Create Date: 2017-03-15 10:48:00.515745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f816aa90812'
down_revision = 'edb5ca91f83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('country', sa.String(length=2)))
    op.execute('update groups set country = \'\'')
    op.alter_column('groups', 'country', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'country')
    # ### end Alembic commands ###
