"""adding rituximab baseline assessement table

Revision ID: 2a9e926a2c55
Revises: a5b4d47313ee
Create Date: 2018-05-08 14:39:05.722000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a9e926a2c55'
down_revision = 'a5b4d47313ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline_assessment',
    sa.Column('id', postgresql.UUID(), server_default=sa.text(u'uuid_generate_v4()'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('supportive_medication', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_treatment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance_status', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('modified_user_id', sa.Integer(), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baseline_assessment')
    # ### end Alembic commands ###
