"""remove status from diagnosis

Revision ID: 2e5e536d3a26
Revises: e23d1a7e678d
Create Date: 2018-09-10 12:51:29.408083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5e536d3a26'
down_revision = 'e23d1a7e678d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nurture_samples_options', ['id'])
    op.drop_column('patient_diagnoses', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_diagnoses', sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nurture_samples_options', type_='unique')
    # ### end Alembic commands ###
