"""add relapse sample taken flag

Revision ID: 2fa1fc489998
Revises: 693abc12670c
Create Date: 2018-05-25 09:40:20.426900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa1fc489998'
down_revision = '693abc12670c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ins_relapses', sa.Column('relapse_sample_taken', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ins_relapses', 'relapse_sample_taken')
    # ### end Alembic commands ###
