"""add discharged back to gp field

Revision ID: 4f0a095a3c25
Revises: ea9ca52c81d1
Create Date: 2019-05-15 09:07:50.866766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4f0a095a3c25"
down_revision = "ea9ca52c81d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_patients", sa.Column("discharged_date", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group_patients", "discharged_date")
    # ### end Alembic commands ###
