"""added more rituximab selection criteria

Revision ID: 544aa435c17d
Revises: 4f0a095a3c25
Create Date: 2019-06-03 09:25:12.114591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "544aa435c17d"
down_revision = "4f0a095a3c25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rituximab_baseline_assessment",
        "comorbidities",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.add_column("rituximab_criteria", sa.Column("mood_disturbance", sa.Boolean(), nullable=True))
    op.add_column(
        "rituximab_criteria", sa.Column("osteoporosis_osteopenia", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "rituximab_criteria", sa.Column("previous_hospitalization", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rituximab_criteria", "previous_hospitalization")
    op.drop_column("rituximab_criteria", "osteoporosis_osteopenia")
    op.drop_column("rituximab_criteria", "mood_disturbance")
    op.alter_column(
        "rituximab_baseline_assessment",
        "comorbidities",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    # ### end Alembic commands ###
