"""rituximab consent rename to criteria

Revision ID: 578d64b20973
Revises: d2171e3e322b
Create Date: 2018-08-08 10:05:53.812370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '578d64b20973'
down_revision = 'd2171e3e322b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rituximab_criteria',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('criteria1', sa.Boolean(), nullable=True),
    sa.Column('criteria2', sa.Boolean(), nullable=True),
    sa.Column('criteria3', sa.Boolean(), nullable=True),
    sa.Column('criteria4', sa.Boolean(), nullable=True),
    sa.Column('criteria5', sa.Boolean(), nullable=True),
    sa.Column('criteria6', sa.Boolean(), nullable=True),
    sa.Column('criteria7', sa.Boolean(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_user_id', sa.Integer(), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rituximab_consents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rituximab_consents',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('criteria1', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criteria2', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criteria3', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criteria4', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criteria5', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criteria6', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criteria7', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modified_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], name='rituximab_consents_created_user_id_fkey'),
    sa.ForeignKeyConstraint(['modified_user_id'], ['users.id'], name='rituximab_consents_modified_user_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='rituximab_consents_patient_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='rituximab_consents_pkey')
    )
    op.drop_table('rituximab_criteria')
    # ### end Alembic commands ###
