"""add countries

Revision ID: 68e770e3b9b6
Revises: 1f816aa90812
Create Date: 2017-03-15 13:36:17.837983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e770e3b9b6'
down_revision = '1f816aa90812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.alter_column(u'groups', 'country',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.create_foreign_key(None, 'groups', 'countries', ['country'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.alter_column(u'groups', 'country',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.drop_table('countries')
    # ### end Alembic commands ###
