"""add ins relapse dipsticks

Revision ID: 693abc12670c
Revises: c98e6f64037f
Create Date: 2018-05-24 09:08:25.858957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693abc12670c'
down_revision = 'c98e6f64037f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ins_relapses', sa.Column('peak_protein_dipstick', sa.String(), nullable=True))
    op.add_column('ins_relapses', sa.Column('remission_protein_dipstick', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ins_relapses', 'remission_protein_dipstick')
    op.drop_column('ins_relapses', 'peak_protein_dipstick')
    # ### end Alembic commands ###
