"""add country to a group

Revision ID: 6e34e92cec6f
Revises: da93beb77564
Create Date: 2017-03-16 09:42:39.857250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e34e92cec6f'
down_revision = 'da93beb77564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'groups', sa.Column('country_code', sa.String(), nullable=True))
    op.create_foreign_key('groups_country_code_fkey', 'groups', 'countries', ['country_code'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_country_code_fkey', 'groups', type_='foreignkey')
    op.drop_column(u'groups', 'country_code')
    # ### end Alembic commands ###
