"""add comorbidities field to rituximab

Revision ID: 8c976165517c
Revises: 4f24b92626f4
Create Date: 2019-01-30 14:51:13.328000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c976165517c'
down_revision = '4f24b92626f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rituximab_baseline_assessment', sa.Column('comorbidities', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rituximab_baseline_assessment', 'comorbidities')
    # ### end Alembic commands ###
