"""add type and weight to consent model

Revision ID: 98860d4e5dfb
Revises: cdf9ed2d5bd1
Create Date: 2017-11-02 08:21:50.660018

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98860d4e5dfb'
down_revision = 'cdf9ed2d5bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    consent_type_type = postgresql.ENUM('FORM', 'INFORMATION_SHEET', name='consent_type_type')
    consent_type_type.create(op.get_bind())

    op.add_column('consents', sa.Column('consent_type', sa.Enum('FORM', 'INFORMATION_SHEET', name="consent_type_type"), nullable=True))
    consent_type = sa.table('consents', sa.column('consent_type'))
    op.execute(consent_type.update().values(consent_type='FORM'))
    op.alter_column('consents', 'consent_type', nullable=False)


    op.add_column('consents', sa.Column('weight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('consents', 'weight')
    op.drop_column('consents', 'consent_type')
    enum_type = sa.Enum(name='consent_type_type')
    enum_type.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
