"""rename rituximab selection criteria column

Revision ID: 99da04e11317
Revises: e23d1a7e678d
Create Date: 2018-10-05 13:35:47.380000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99da04e11317'
down_revision = 'e23d1a7e678d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rituximab_criteria', 'therapy_failure', nullable=True, new_column_name='ongoing_severe_disease')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rituximab_criteria', 'ongoing_severe_disease', nullable=True, new_column_name='therapy_failure')
    # ### end Alembic commands ###
