"""add column to hold swan field

Revision ID: 9f1f5f15d8e0
Revises: dd73a75ce20c
Create Date: 2018-02-07 12:54:55.786543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1f5f15d8e0'
down_revision = 'dd73a75ce20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_diagnoses', sa.Column('swan', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_diagnoses', 'swan')
    # ### end Alembic commands ###
