"""swapped enum for table

Revision ID: c6413ac84577
Revises: 0a1d6e065731
Create Date: 2026-01-08 12:35:36.744285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6413ac84577'
down_revision = '0a1d6e065731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antibodies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_antibodies',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('antibody_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['antibody_id'], ['antibodies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'antibody_id')
    )
    op.drop_column('patient_diagnoses', 'antibodies')
    op.add_column('patient_diagnoses', sa.Column('antibody_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'patient_diagnoses', 'antibodies', ['antibody_id'], ['id'])




def downgrade():
    op.add_column('patient_diagnoses', sa.Column('antibodies', postgresql.ENUM('Anti-PLA2R', 'Anti-THSD7A', name='antibody_type_enum'), autoincrement=False, nullable=True))
    op.drop_table('group_antibodies')
    op.drop_table('antibodies')
    # ### end Alembic commands ###
