"""add default nurture tubes values

Revision ID: c747d6f9d206
Revises: c9b69c2c665d
Create Date: 2017-05-16 10:21:00.181786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from radar.models.nurture_tubes import PROTOCOL_OPTION_TYPE, SampleOption

# revision identifiers, used by Alembic.
revision = 'c747d6f9d206'
down_revision = 'c9b69c2c665d'
branch_labels = None
depends_on = None

from sqlalchemy.orm import sessionmaker
Session = sessionmaker()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurture_samples_options',
    sa.Column('id', sa.Enum('ADULT', 'CHILDREN15_2ND', 'CHILDREN15_B', 'CHILDREN_LESS_15_2ND', 'CHILDREN_LESS_15_B', 'CHILDREN30_2ND', 'CHILDREN30_B', name='protocol_option_type'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('epa', sa.Integer(), nullable=True),
    sa.Column('epb', sa.Integer(), nullable=True),
    sa.Column('lpa', sa.Integer(), nullable=True),
    sa.Column('lpb', sa.Integer(), nullable=True),
    sa.Column('uc', sa.Integer(), nullable=True),
    sa.Column('ub', sa.Integer(), nullable=True),
    sa.Column('ud', sa.Integer(), nullable=True),
    sa.Column('fub', sa.Integer(), nullable=True),
    sa.Column('sc', sa.Integer(), nullable=True),
    sa.Column('sa', sa.Integer(), nullable=True),
    sa.Column('sb', sa.Integer(), nullable=True),
    sa.Column('rna', sa.Integer(), nullable=True),
    sa.Column('wb', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('protocol')
    )
    op.add_column(u'nurture_samples', sa.Column('protocol_id', sa.Enum('ADULT', 'CHILDREN15_2ND', 'CHILDREN15_B', 'CHILDREN_LESS_15_2ND', 'CHILDREN_LESS_15_B', 'CHILDREN30_2ND', 'CHILDREN30_B', name='protocol_option_type'), nullable=False))
    op.create_foreign_key('nurture_samples_protocol_id_fkey', 'nurture_samples', 'nurture_samples_options', ['protocol_id'], ['id'])
    op.drop_column(u'nurture_samples', 'protocol')
    bind = op.get_bind()
    session = Session(bind=bind)

    session.add(SampleOption(id=PROTOCOL_OPTION_TYPE('ADULT'), label='Adult', epa=18, epb=3, lpa=19, lpb=2, uc=1, ub=24, ud=1, fub=10, sc=1, sa=46, sb=4, rna=1, wb=3))
    session.add(SampleOption(id=PROTOCOL_OPTION_TYPE('CHILDREN30_B'), label='Children >30kg NS Baseline, Disease F.Up', epa=11, epb=1, lpa=9, lpb=1, uc=1, ub=24, ud=1, fub=10, sc=1, sa=30))
    session.add(SampleOption(id=PROTOCOL_OPTION_TYPE('CHILDREN30_2ND'), label='Children >30kg NS 2nd visit', epa=10, epb=1, lpa=10, lpb=1, sa=12, rna=1, wb=3))
    session.add(SampleOption(id=PROTOCOL_OPTION_TYPE('CHILDREN15_B'), label='Children 15-30kg NS Baseline, Disease F.Up', epa=7, epb=1, uc=1, ub=24, ud=1, fub=10, sc=1, sa=13))
    session.add(SampleOption(id=PROTOCOL_OPTION_TYPE('CHILDREN15_2ND'), label='Children 15-30kg NS 2nd visit', sa=12, wb=2))
    session.add(SampleOption(id=PROTOCOL_OPTION_TYPE('CHILDREN_LESS_15_B'), label='Children <15kg NS Baseline, Disease F.Up', uc=1, ub=12, ud=1, fub=4, sc=1, sa=8))
    session.add(SampleOption(id=PROTOCOL_OPTION_TYPE('CHILDREN_LESS_15_2ND'), label='Children <15kg NS 2nd visit', wb=2))

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'nurture_samples', sa.Column('protocol', sa.VARCHAR(), autoincrement=False, default='Adult'))
    op.drop_constraint('nurture_samples_protocol_id_fkey', 'nurture_samples', type_='foreignkey')
    op.drop_column(u'nurture_samples', 'protocol_id')
    op.drop_table('nurture_samples_options')
    enum_type = sa.Enum(name='protocol_option_type')
    enum_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
