"""add recurrence flag to transplant

Revision ID: c98e6f64037f
Revises: 2a9e926a2c55
Create Date: 2018-05-24 08:11:08.112555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98e6f64037f'
down_revision = '2a9e926a2c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transplants', sa.Column('recurrence', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transplants', 'recurrence')
    # ### end Alembic commands ###
