"""add nurture tubes samples

Revision ID: c9b69c2c665d
Revises: d4e81c8c52b9
Create Date: 2017-05-12 10:46:50.031512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9b69c2c665d'
down_revision = 'd4e81c8c52b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurture_samples',
    sa.Column('id', postgresql.UUID(), server_default=sa.text(u'uuid_generate_v4()'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('barcode', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('epa', sa.Integer(), nullable=True),
    sa.Column('epb', sa.Integer(), nullable=True),
    sa.Column('lpa', sa.Integer(), nullable=True),
    sa.Column('lpb', sa.Integer(), nullable=True),
    sa.Column('uc', sa.Integer(), nullable=True),
    sa.Column('ub', sa.Integer(), nullable=True),
    sa.Column('ud', sa.Integer(), nullable=True),
    sa.Column('fub', sa.Integer(), nullable=True),
    sa.Column('sc', sa.Integer(), nullable=True),
    sa.Column('sa', sa.Integer(), nullable=True),
    sa.Column('sb', sa.Integer(), nullable=True),
    sa.Column('rna', sa.Integer(), nullable=True),
    sa.Column('wb', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('modified_user_id', sa.Integer(), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('samples_patient_idx', 'nurture_samples', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('samples_patient_idx', table_name='nurture_samples')
    op.drop_table('nurture_samples')
    # ### end Alembic commands ###
