"""Add consents

Revision ID: cdf9ed2d5bd1
Revises: dd6140eb552f
Create Date: 2017-10-17 14:46:27.084805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf9ed2d5bd1'
down_revision = 'dd6140eb552f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('paediatric', sa.Boolean(), server_default=sa.text(u'false'), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('retired', sa.Boolean(), server_default=sa.text(u'false')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('signed_on_date', sa.Date(), nullable=False),
    sa.Column('withdrawn_on_date', sa.Date(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('modified_user_id', sa.Integer(), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], ),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_consents')
    op.drop_table('consents')
    # ### end Alembic commands ###
