"""add consents

Revision ID: d2171e3e322b
Revises: 6b65805e6dc6
Create Date: 2018-07-09 14:11:25.289032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2171e3e322b'
down_revision = '6b65805e6dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rituximab_consents',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('criteria1', sa.Boolean(), nullable=True),
    sa.Column('criteria2', sa.Boolean(), nullable=True),
    sa.Column('criteria3', sa.Boolean(), nullable=True),
    sa.Column('criteria4', sa.Boolean(), nullable=True),
    sa.Column('criteria5', sa.Boolean(), nullable=True),
    sa.Column('criteria6', sa.Boolean(), nullable=True),
    sa.Column('criteria7', sa.Boolean(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_user_id', sa.Integer(), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rituximab_consents')
    # ### end Alembic commands ###
