"""Add ins relapse fields

Revision ID: d7a47953addd
Revises: 98860d4e5dfb
Create Date: 2018-01-23 07:26:06.106000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a47953addd'
down_revision = '98860d4e5dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ins_relapses', sa.Column('peak_acr', sa.Float(), nullable=True))
    op.add_column('ins_relapses', sa.Column('peak_pcr', sa.Float(), nullable=True))
    op.add_column('ins_relapses', sa.Column('remission_acr', sa.Float(), nullable=True))
    op.add_column('ins_relapses', sa.Column('remission_pcr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ins_relapses', 'remission_pcr')
    op.drop_column('ins_relapses', 'remission_acr')
    op.drop_column('ins_relapses', 'peak_pcr')
    op.drop_column('ins_relapses', 'peak_acr')
    # ### end Alembic commands ###
