"""create countries table with data

Revision ID: da93beb77564
Revises: 
Create Date: 2017-03-16 09:15:50.966604

"""
from alembic import op
import sqlalchemy as sa

from radar.models.patient_addresses import COUNTRIES
from radar.models.countries import Country


# revision identifiers, used by Alembic.
revision = 'da93beb77564'
down_revision = None
branch_labels = None
depends_on = None

from sqlalchemy.orm import sessionmaker
Session = sessionmaker()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )

    bind = op.get_bind()
    session = Session(bind=bind)
    countries = [Country(code=code, label=label) for code, label in COUNTRIES.items()]
    session.add_all(countries)
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
