"""adding rituximab criteria specifying fields

Revision ID: e23d1a7e678d
Revises: 578d64b20973
Create Date: 2018-08-09 09:31:23.670581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23d1a7e678d'
down_revision = '578d64b20973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rituximab_criteria', sa.Column('alkylating_complication', sa.Boolean(), nullable=True))
    op.add_column('rituximab_criteria', sa.Column('alkylating_failure_monitoring_requirements', sa.Boolean(), nullable=True))
    op.add_column('rituximab_criteria', sa.Column('cancer', sa.Boolean(), nullable=True))
    op.add_column('rituximab_criteria', sa.Column('cni_failure_monitoring_requirements', sa.Boolean(), nullable=True))
    op.add_column('rituximab_criteria', sa.Column('cni_therapy_complication', sa.Boolean(), nullable=True))
    op.add_column('rituximab_criteria', sa.Column('diabetes', sa.Boolean(), nullable=True))
    op.add_column('rituximab_criteria', sa.Column('drug_associated_toxicity', sa.Boolean(), nullable=True))
    op.add_column('rituximab_criteria', sa.Column('fall_in_egfr', sa.Boolean(), nullable=True))
    op.add_column('rituximab_criteria', sa.Column('hypersensitivity', sa.Boolean(), nullable=True))
    op.add_column('rituximab_criteria', sa.Column('risk_factors', sa.Boolean(), nullable=True))
    op.add_column('rituximab_criteria', sa.Column('therapy_failure', sa.Boolean(), nullable=True))
    op.add_column('rituximab_criteria', sa.Column('threatened_fertility', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rituximab_criteria', 'threatened_fertility')
    op.drop_column('rituximab_criteria', 'therapy_failure')
    op.drop_column('rituximab_criteria', 'risk_factors')
    op.drop_column('rituximab_criteria', 'hypersensitivity')
    op.drop_column('rituximab_criteria', 'fall_in_egfr')
    op.drop_column('rituximab_criteria', 'drug_associated_toxicity')
    op.drop_column('rituximab_criteria', 'diabetes')
    op.drop_column('rituximab_criteria', 'cni_therapy_complication')
    op.drop_column('rituximab_criteria', 'cni_failure_monitoring_requirements')
    op.drop_column('rituximab_criteria', 'cancer')
    op.drop_column('rituximab_criteria', 'alkylating_failure_monitoring_requirements')
    op.drop_column('rituximab_criteria', 'alkylating_complication')
    # ### end Alembic commands ###
