"""graft loss cause move to transplant

Revision ID: ea9ca52c81d1
Revises: 751044a5528a
Create Date: 2019-03-06 07:21:39.852000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea9ca52c81d1'
down_revision = '751044a5528a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transplant_rejections', 'graft_loss_cause')
    op.add_column('transplants', sa.Column('graft_loss_cause', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transplants', 'graft_loss_cause')
    op.add_column('transplant_rejections', sa.Column('graft_loss_cause', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
