"""make ethnicities tables

Revision ID: f20cde35e83c
Revises: 4b7643dcbef6
Create Date: 2017-03-13 10:48:04.665115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20cde35e83c'
down_revision = '4b7643dcbef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ethnicities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_ethnicities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('ethnicity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ethnicity_id'], ['ethnicities.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'patient_demographics', sa.Column('ethnicity_id', sa.Integer(), nullable=True))
    op.create_foreign_key('patient_demographics_ethnicity_id_fkey', 'patient_demographics', 'ethnicities', ['ethnicity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_demographics_ethnicity_id_fkey', 'patient_demographics', type_='foreignkey')
    op.drop_column(u'patient_demographics', 'ethnicity_id')
    op.drop_table('group_ethnicities')
    op.drop_table('ethnicities')
    # ### end Alembic commands ###
