"""add extra fields to rituximab baseline assessment

Revision ID: f74be8e596da
Revises: 2fa1fc489998
Create Date: 2018-06-12 14:03:03.711465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f74be8e596da'
down_revision = '2fa1fc489998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rituximab_baseline_assessment', sa.Column('nephropathies', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('rituximab_baseline_assessment', sa.Column('past_remission', sa.Boolean(), nullable=True))
    op.add_column('rituximab_baseline_assessment', sa.Column('relapsed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rituximab_baseline_assessment', 'relapsed')
    op.drop_column('rituximab_baseline_assessment', 'past_remission')
    op.drop_column('rituximab_baseline_assessment', 'nephropathies')
    # ### end Alembic commands ###
