UNIT_VIEW_PATIENT_ROLES = [
    'CLINICIAN',
    'SENIOR_CLINICIAN',
    'UNIT_ADMIN',
]

UNIT_MODIFY_PATIENT_ROLES = [
    'CLINICIAN',
    'SENIOR_CLINICIAN',
]

UNIT_DEMOGRAPHICS_ROLES = [
    'CLINICIAN',
    'SENIOR_CLINICIAN',
    'UNIT_ADMIN',
]

DISEASE_GROUP_VIEW_PATIENT_ROLES = [
    'SENIOR_RESEARCHER',
    'RESEARCHER'
]

DISEASE_GROUP_DEMOGRAPHICS_ROLES = [
    'SENIOR_RESEARCHER',
]