ADDRESSES = 'ADDRESSES'
ALIASES = 'ALIASES'
COHORTS = 'COHORTS'
COMORBIDITIES = 'COMORBIDITIES'
DEMOGRAPHICS = 'DEMOGRAPHICS'
DIAGNOSES = 'DIAGNOSES'
DIALYSIS = 'DIALYSIS'
FAMILY_HISTORY = 'FAMILY_HISTORY'
GENETICS = 'GENETICS'
HOSPITALISATIONS = 'HOSPITALISATIONS'
MEDICATIONS = 'MEDICATIONS'
NUMBERS = 'NUMBERS'
PATHOLOGY = 'PATHOLOGY'
PLASMAPHERESIS = 'PLASMAPHERESIS'
RENAL_IMAGING = 'RENAL_IMAGING'
RESULTS = 'RESULTS'
SALT_WASTING_CLINICAL_FEATURES = 'SALT_WASTING_CLINICAL_FEATURES'
TRANSPLANTS = 'TRANSPLANTS'
UNITS = 'UNITS'

FEATURES = [
    ADDRESSES,
    ALIASES,
    COHORTS,
    COMORBIDITIES,
    DEMOGRAPHICS,
    DIAGNOSES,
    DIALYSIS,
    FAMILY_HISTORY,
    GENETICS,
    HOSPITALISATIONS,
    MEDICATIONS,
    NUMBERS,
    PATHOLOGY,
    PLASMAPHERESIS,
    RENAL_IMAGING,
    RESULTS,
    SALT_WASTING_CLINICAL_FEATURES,
    TRANSPLANTS,
    UNITS,
]
