from collections import OrderedDict

# =====
# Roles
# =====

ORGANISATION_IT = 'IT'
ORGANISATION_ADMIN = 'ADMIN'
ORGANISATION_CLINICIAN = 'CLINICIAN'
ORGANISATION_SENIOR_CLINICIAN = 'SENIOR_CLINICIAN'

COHORT_SENIOR_RESEARCHER = 'SENIOR_RESEARCHER'
COHORT_RESEARCHER = 'RESEARCHER'

ORGANISATION_ROLE_NAMES = {
    ORGANISATION_IT: 'IT',
    ORGANISATION_ADMIN: 'Admin',
    ORGANISATION_CLINICIAN: 'Clinician',
    ORGANISATION_SENIOR_CLINICIAN: 'Senior Clinician',
}

DISEASE_GROUP_ROLE_NAMES = {
    COHORT_SENIOR_RESEARCHER: 'Senior Researcher',
    COHORT_RESEARCHER: 'Researcher',
}

ORGANISATION_ROLES = OrderedDict([
    (ORGANISATION_SENIOR_CLINICIAN, 'Senior Clinician'),
    (ORGANISATION_CLINICIAN, 'Clinician'),
    (ORGANISATION_ADMIN, 'Admin'),
    (ORGANISATION_IT, 'IT'),
])

COHORT_ROLES = OrderedDict([
    (COHORT_RESEARCHER, 'Researcher'),
    (COHORT_SENIOR_RESEARCHER, 'Senior Researcher'),
])

# Special roles

ORGANISATION_GOD = 'GOD'
COHORT_GOD = 'GOD'

# ===========
# Permissions
# ===========

# Unit permissions

ORGANISATION_VIEW_PATIENT_ROLES = [
    ORGANISATION_GOD,
    ORGANISATION_CLINICIAN,
    ORGANISATION_SENIOR_CLINICIAN,
    ORGANISATION_ADMIN,
]

ORGANISATION_EDIT_PATIENT_ROLES = [
    ORGANISATION_GOD,
    ORGANISATION_CLINICIAN,
    ORGANISATION_SENIOR_CLINICIAN,
]

ORGANISATION_RECRUIT_PATIENT_ROLES = [
    ORGANISATION_GOD,
    ORGANISATION_CLINICIAN,
    ORGANISATION_SENIOR_CLINICIAN,
]

# TODO Rename to DEMOGRAPHICS
ORGANISATION_VIEW_DEMOGRAPHICS_ROLES = [
    ORGANISATION_GOD,
    ORGANISATION_CLINICIAN,
    ORGANISATION_SENIOR_CLINICIAN,
    ORGANISATION_ADMIN,
]

ORGANISATION_VIEW_USER_ROLES = [
    ORGANISATION_GOD,
    ORGANISATION_IT,
    ORGANISATION_ADMIN,
    ORGANISATION_SENIOR_CLINICIAN,
]

ORGANISATION_MANAGED_ROLES = {
    ORGANISATION_IT: [
        ORGANISATION_CLINICIAN,
    ],
    ORGANISATION_ADMIN: [
        ORGANISATION_CLINICIAN,
    ],
    ORGANISATION_SENIOR_CLINICIAN: [
        ORGANISATION_CLINICIAN,
    ],
}

# Cohort permissions

COHORT_VIEW_PATIENT_ROLES = [
    COHORT_SENIOR_RESEARCHER,
    COHORT_RESEARCHER,
    COHORT_GOD
]

COHORT_VIEW_DEMOGRAPHICS_ROLES = [
    COHORT_SENIOR_RESEARCHER,
    COHORT_GOD
]

COHORT_VIEW_USER_ROLES = [
    COHORT_GOD
]

COHORT_MANAGED_ROLES = {
    COHORT_SENIOR_RESEARCHER: [
        COHORT_SENIOR_RESEARCHER,
        COHORT_RESEARCHER
    ]
}
